# fly.toml app configuration file generated for test-jupiter-swap-api on 2023-12-04T14:14:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "<APP_NAME>"
primary_region = "sin"

[build]
image = "ghcr.io/jup-ag/jupiter-swap-api:latest"

[deploy]
strategy = "bluegreen"

[env]
PORT = "8080"
RPC_URL = "<RPC_URL>"
# YELLOWSTONE_GRPC_ENDPOINT = "" # Optional 
# YELLOWSTONE_GRPC_X_TOKEN = "" # Optional

[http_service]
internal_port = 8080
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
[http_service.concurrency]
type = "requests"
hard_limit = 30
soft_limit = 10

[[http_service.checks]]
interval = "30s"
timeout = "5s"
grace_period = "20s"
method = "GET"
path = "/program-id-to-label"

[[vm]]
cpu_kind = "performance"
cpus = 8
memory_mb = 16384
